//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class n_o_s
    {
        public int id { get; set; }
        public string organisation_id { get; set; }
        public string test_facility_id { get; set; }
        public string no_user_id { get; set; }
        public string no_name { get; set; }
        public string no_email { get; set; }
        public string no_details { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
