//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_histories
    {
        public int id { get; set; }
        public string order_id { get; set; }
        public Nullable<int> no_of_sample { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string description { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> payment_status { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
