//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_VendorGeneralInfo
    {
        public long VendorDetailID { get; set; }
        public string VendorRefNo { get; set; }
        public string RUNNo { get; set; }
        public string LogoPath { get; set; }
        public string RegistrationCategory { get; set; }
        public string TypeOfOwnership { get; set; }
        public string BuisnessSector { get; set; }
        public Nullable<System.DateTime> Date_Incorportaion_Company { get; set; }
        public string CompanyURL { get; set; }
        public string Street_Address { get; set; }
        public string Street_Address_Line_2 { get; set; }
        public string MobileNo { get; set; }
        public string ContactNo { get; set; }
        public string FaxNo { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public string TANNo { get; set; }
        public string UAMNo { get; set; }
        public string CINNo { get; set; }
        public string IsSubmit { get; set; }
        public string IsVerify { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
