//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_VendorPlantorMachine
    {
        public long PlanMachineId { get; set; }
        public string MachineModelSpec { get; set; }
        public string Make { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> DateofPurchase { get; set; }
        public string Usage { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string VendorRefno { get; set; }
    }
}
