//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Factory
    {
        public long FactoryID { get; set; }
        public string CompanyRefNo { get; set; }
        public string FactoryName { get; set; }
        public string FactoryRefNo { get; set; }
        public string FactoryAddress { get; set; }
        public Nullable<int> FactoryStateID { get; set; }
        public string FactoryDistrict { get; set; }
        public string FactoryPincode { get; set; }
        public string FactoryCEOName { get; set; }
        public string FactoryCEOEmail { get; set; }
        public string FactoryTelephoneNo { get; set; }
        public string FactoryFaxNo { get; set; }
        public string FactoryEmailID { get; set; }
        public string FactoryWebsite { get; set; }
        public string NodalOfficeRefNo { get; set; }
        public string FactoryGSTNo { get; set; }
        public string FactoryCINNo { get; set; }
        public string FactoryPANNo { get; set; }
        public string FactoryIECode { get; set; }
        public string FactoryNodalOfficerEmailId { get; set; }
        public string ChnFactoryPassword { get; set; }
        public string FactoryFacebook { get; set; }
        public string FactoryTwitter { get; set; }
        public string FactoryLinkedin { get; set; }
        public string FactoryInstagram { get; set; }
        public string Factorylatitude { get; set; }
        public string Factorylongitude { get; set; }
        public string DefaultPagexx { get; set; }
        public string Salt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string Role { get; set; }
        public string IsActive { get; set; }
    }
}
