//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_NicCode
    {
        public long NicCodeID { get; set; }
        public string Lenth { get; set; }
        public string NicCode { get; set; }
        public string NicDesc { get; set; }
        public string Schedule { get; set; }
        public string AdminstritiveMinistryCode { get; set; }
        public string NegativeList { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
