//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_VendorOutsourceFac
    {
        public long OutFacId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string MainEquip { get; set; }
        public string TestEquip { get; set; }
        public string Process { get; set; }
        public string NameandDetail { get; set; }
        public string Vendorrefno { get; set; }
    }
}
