//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_VendorFinancialBank
    {
        public long FinancialAccountId { get; set; }
        public string VendorRefNo { get; set; }
        public string NameofBank { get; set; }
        public string TypeOfAccount { get; set; }
        public string AccountNo { get; set; }
        public string MICRNo { get; set; }
        public string IFSCCode { get; set; }
        public string File_Bank_Solvency_Certificate { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
