//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_VendorRegistration
    {
        public long VendorID { get; set; }
        public string RunNo { get; set; }
        public string VendorRefNo { get; set; }
        public string PanNo { get; set; }
        public string GSTNo { get; set; }
        public string V_CompName { get; set; }
        public string V_RegisterdDPSU { get; set; }
        public string AuthorizationLetter { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string IsActive { get; set; }
        public string InviteDPSU { get; set; }
        public string IsInvitation { get; set; }
        public string CheckStatus { get; set; }
    }
}
