//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_RequestInfo
    {
        public long RequestID { get; set; }
        public string RequestBy { get; set; }
        public string RequestCompName { get; set; }
        public Nullable<long> RequestMobileNo { get; set; }
        public string RequestAddress { get; set; }
        public string RequestEmail { get; set; }
        public string RequestProduct { get; set; }
        public string IsMailSend { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.TimeSpan> RequestTime { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string RequestMCompName { get; set; }
        public string IsActive { get; set; }
        public string PanCard { get; set; }
    }
}
