//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_VendorEmpDetail
    {
        public long EmpId { get; set; }
        public string TotalEmp { get; set; }
        public string Administrative { get; set; }
        public string Technical { get; set; }
        public string Nontechnical { get; set; }
        public string QC { get; set; }
        public string SkilledLabour { get; set; }
        public string Unskilledlabour { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string vendorrefno { get; set; }
    }
}
