//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_HelpDesk
    {
        public long HelpDeskId { get; set; }
        public string IssueRefNo { get; set; }
        public string HFrom { get; set; }
        public string QueryFor { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<long> MobileNo { get; set; }
        public string State { get; set; }
        public string Subject { get; set; }
        public string Address { get; set; }
        public string Issue { get; set; }
        public string Files { get; set; }
        public Nullable<System.DateTime> RiseDate { get; set; }
        public Nullable<System.TimeSpan> RiseTime { get; set; }
        public string IsOpen { get; set; }
        public Nullable<System.DateTime> IsCloseDate { get; set; }
        public string IsCloseBy { get; set; }
        public Nullable<int> IsCloseLevel { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public Nullable<long> SubSubjectId { get; set; }
        public Nullable<long> Status { get; set; }
    }
}
