//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_book_orders
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string test_id { get; set; }
        public string organisation_id { get; set; }
        public string discipline { get; set; }
        public string lab { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> no_of_sample { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public string dimension_eqpt { get; set; }
        public string weight_eqpt { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string duration { get; set; }
        public string attachment { get; set; }
        public string description { get; set; }
        public string Rejectremark { get; set; }
        public Nullable<int> Bookingstatus { get; set; }
        public string report_file { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> payment_status { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
    }
}
