//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_UserLogin
    {
        public int UserID { get; set; }
        public string UserlEmpCode { get; set; }
        public string RefNo { get; set; }
        public string UserName { get; set; }
        public string UserDepartment { get; set; }
        public string UserDesignation { get; set; }
        public string UserEmail { get; set; }
        public string UserMobile { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Postalcode { get; set; }
        public string UserTelephone { get; set; }
        public string UserFax { get; set; }
        public string CompanyRefNo { get; set; }
        public string Type { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string TempRef { get; set; }
        public string IsActive { get; set; }
        public string IsLoginActive { get; set; }
        public string IsUser { get; set; }
        public string DefaultPage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> RecTime { get; set; }
    }
}
