//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_NodalOfficerLogin
    {
        public long NodalOfficerID { get; set; }
        public string NodalEmpCode { get; set; }
        public string NodalOfficerRefNo { get; set; }
        public string NodalOficerName { get; set; }
        public Nullable<int> NodalOfficerDepartment { get; set; }
        public Nullable<int> NodalOfficerDesignation { get; set; }
        public string NodalOfficerEmail { get; set; }
        public string NodalOfficerMobile { get; set; }
        public string NodalOfficerTelephone { get; set; }
        public string NodalOfficerFax { get; set; }
        public string CompanyRefNo { get; set; }
        public string Type { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string TempRef { get; set; }
        public string IsActive { get; set; }
        public string IsLoginActive { get; set; }
        public string IsNodalOfficer { get; set; }
        public string DefaultPage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> RecTime { get; set; }
        public string authorizationLetter { get; set; }
        public string identityID { get; set; }
    }
}
