//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_ProductFIIG
    {
        public long FiigID { get; set; }
        public string ProductRefNo { get; set; }
        public string SCategoryName { get; set; }
        public string Remarks { get; set; }
        public string Remarks2 { get; set; }
        public string Remarks3 { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
