//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_VendorProducedSupplied
    {
        public long VSupplyId { get; set; }
        public string VendorRefNo { get; set; }
        public string Reputed_Customer { get; set; }
        public string Description { get; set; }
        public string SupplyNoDate { get; set; }
        public string OrderQuantity { get; set; }
        public string SuppliedQuantity { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string Type { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
