//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_SubCategory
    {
        public int SCategoryId { get; set; }
        public Nullable<int> PId { get; set; }
        public string L1Code { get; set; }
        public string L2Code { get; set; }
        public string FIIG_No { get; set; }
        public string SCategoryName { get; set; }
        public string SDisplayName { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string IsActive { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
