//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_VendorOEM
    {
        public long OemId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string VendorRefNo { get; set; }
        public string Name { get; set; }
        public string OEM { get; set; }
        public string Address { get; set; }
        public string OfficialName { get; set; }
        public Nullable<long> Phone { get; set; }
        public Nullable<long> Fax { get; set; }
        public string Email { get; set; }
        public string Authrization { get; set; }
    }
}
