//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_VendorServiceDetails
    {
        public long ServiceId { get; set; }
        public string VendorRefno { get; set; }
        public string ServiceNomenclature { get; set; }
        public Nullable<long> Category { get; set; }
        public Nullable<long> SubCategory { get; set; }
        public string Capacity { get; set; }
        public string SACCode { get; set; }
        public string VerifiedDPSU { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
