//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_VendorManuFac
    {
        public long ManuFacId { get; set; }
        public string VendorRefNo { get; set; }
        public string NameOfFactory { get; set; }
        public string FACGSTNO { get; set; }
        public string CAddress { get; set; }
        public string COfficialName { get; set; }
        public string TeleNo { get; set; }
        public string FaxNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
