//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_VendorNodal
    {
        public long VNodelId { get; set; }
        public string VendorRefNo { get; set; }
        public string NodalOfficerName { get; set; }
        public Nullable<long> NodalOfficerMobile { get; set; }
        public string NodalOfficerEmail { get; set; }
        public string Salt { get; set; }
        public string NodalPassword { get; set; }
        public string MasterAllowed { get; set; }
        public string Role { get; set; }
        public string DefaultPage { get; set; }
        public string IsActive { get; set; }
        public string IsLoginActive { get; set; }
        public string IsEmailVerify { get; set; }
        public string IsChangePassword { get; set; }
        public string IsEsignVerify { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public System.DateTime RecInsTime { get; set; }
        public string TempSaltResult { get; set; }
        public Nullable<System.DateTime> PasswordChangeValidTime { get; set; }
    }
}
