//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_StoreIPAddress
    {
        public long Id { get; set; }
        public string ProductRefNo { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> VisitedDate { get; set; }
        public Nullable<System.TimeSpan> VisitedTime { get; set; }
    }
}
