//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_FeedBack
    {
        public long FeedBackId { get; set; }
        public string FeedBackRefNo { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public Nullable<long> MobileNo { get; set; }
        public string Message { get; set; }
        public string CompanyRefNo { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> FeedBackDate { get; set; }
        public string IsActiveChat { get; set; }
        public string IsClosedChat { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
