//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_ProdQtyPrice
    {
        public long ProdQtyPriceId { get; set; }
        public string ProductRefNo { get; set; }
        public Nullable<long> Year { get; set; }
        public string FYear { get; set; }
        public string EstimatedQty { get; set; }
        public string Unit { get; set; }
        public string EstimatedPrice { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string Type { get; set; }
        public string Type2 { get; set; }
    }
}
