//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Unit
    {
        public long UnitID { get; set; }
        public string FactoryRefNo { get; set; }
        public string UnitName { get; set; }
        public string UnitRefNo { get; set; }
        public string UnitAddress { get; set; }
        public Nullable<int> UnitStateID { get; set; }
        public string UnitDistrict { get; set; }
        public string UnitPincode { get; set; }
        public string UnitCEOName { get; set; }
        public string UnitCEOEmail { get; set; }
        public string UnitTelephoneNo { get; set; }
        public string UnitFaxNo { get; set; }
        public string UnitEmailID { get; set; }
        public string UnitWebsite { get; set; }
        public string NodalOfficeRefNo { get; set; }
        public string UnitFacebook { get; set; }
        public string UnitTwitter { get; set; }
        public string UnitLinkedin { get; set; }
        public string UnitInstagram { get; set; }
        public string Unitlatitude { get; set; }
        public string Unitlongitude { get; set; }
        public string UnitNodalOfficerEmailId { get; set; }
        public string ChngUnitPassword { get; set; }
        public string DefaultPagexx { get; set; }
        public string Salt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string Role { get; set; }
        public string IsActive { get; set; }
    }
}
