//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_PinMaster
    {
        public int PinId { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string PostOfficeName { get; set; }
        public string CityName { get; set; }
        public string CityId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
