//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Category
    {
        public int MCategoryId { get; set; }
        public string MCategoryName { get; set; }
        public string MDisplayName { get; set; }
        public string SCategoryId { get; set; }
        public Nullable<int> MSequence { get; set; }
        public string Flag { get; set; }
        public string IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
