//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_CompanyRemarkReply
    {
        public long Id { get; set; }
        public string RemarkRefNo { get; set; }
        public string R_UserName { get; set; }
        public string R_Email { get; set; }
        public string R_Remark { get; set; }
        public string R_Reply { get; set; }
        public Nullable<System.DateTime> R_Date { get; set; }
        public string R_IsActive { get; set; }
    }
}
