//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_status_reason
    {
        public int id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> reason_id { get; set; }
        public string reason { get; set; }
        public string createdby { get; set; }
    }
}
