//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_HelpDeskTrack
    {
        public long TrackId { get; set; }
        public string TrackRefNo { get; set; }
        public Nullable<int> CommentBy { get; set; }
        public string Comment { get; set; }
        public string CommentFile { get; set; }
        public string IsForword { get; set; }
        public string ReasoneofForword { get; set; }
        public Nullable<long> ForwordFrom { get; set; }
        public Nullable<long> ForwordTo { get; set; }
        public Nullable<System.DateTime> ForwordDate { get; set; }
        public Nullable<System.DateTime> ForwordTime { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string IsClose { get; set; }
        public string CloseReasone { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
