//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_ProdLog
    {
        public long ProdId { get; set; }
        public string PRef { get; set; }
        public string UName { get; set; }
        public string CRef { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string mWork { get; set; }
    }
}
