//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_RequestInfo
    {
        public long mReqTrnId { get; set; }
        public string ProductRefNo { get; set; }
        public Nullable<long> RequestID { get; set; }
        public string CompanyName { get; set; }
        public string Unit { get; set; }
        public string Division { get; set; }
        public string Remark { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string IntShownReason { get; set; }
        public string UserReason { get; set; }
        public Nullable<int> Reasonid { get; set; }
        public string Reasonidname { get; set; }
    }
}
