//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_Log
    {
        public long ID { get; set; }
        public string UserId { get; set; }
        public string IPAddress { get; set; }
        public string SystemName { get; set; }
        public string Form { get; set; }
        public string Activity { get; set; }
        public string LoginDate { get; set; }
        public string LoginTime { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
