//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_VendorTestFacility
    {
        public long TestFacId { get; set; }
        public string TypeofGauge { get; set; }
        public string Make { get; set; }
        public string LeastCount { get; set; }
        public string Measurment { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<System.DateTime> PurchaseYEAR { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string VendorRefNo { get; set; }
    }
}
