//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_VendorFinacialInfo
    {
        public long FinancialInfoId { get; set; }
        public string VendorRefNo { get; set; }
        public string FinancialYear { get; set; }
        public string Value_of_Current_Assets { get; set; }
        public string Value_of_Current_Liabilites { get; set; }
        public string Total_Profit_Loss { get; set; }
        public string File_Audited_Balance_account_sheet { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
