//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_VendorAreaDetails
    {
        public long AreaDetId { get; set; }
        public string NameOfFactory { get; set; }
        public string ProductionArea { get; set; }
        public string InspectionArea { get; set; }
        public string TotalCoverd { get; set; }
        public string TotalArea { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string VendorRefNo { get; set; }
    }
}
