//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_FeedBack
    {
        public long Id { get; set; }
        public string FeedBackRefNo { get; set; }
        public string R_UserName { get; set; }
        public string R_Email { get; set; }
        public string R_Messg { get; set; }
        public Nullable<System.DateTime> R_Date { get; set; }
        public Nullable<System.TimeSpan> R_Time { get; set; }
        public string S_Email { get; set; }
        public string S_Name { get; set; }
        public string S_Question { get; set; }
        public string R_IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
