//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_ProductChangesStatus
    {
        public long ProdID { get; set; }
        public string ProdRefNo { get; set; }
        public string ProductChanges { get; set; }
        public string ChangesBy { get; set; }
        public string Status { get; set; }
        public string Mailsend { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
