//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_VendorCompInfo
    {
        public long VCompInfoId { get; set; }
        public string VendorRefNo { get; set; }
        public string IsLabAccredited { get; set; }
        public string IsSalesOffice { get; set; }
        public string Detail_RDFacility { get; set; }
        public string IsDealer_Distributor { get; set; }
        public Nullable<System.DateTime> IsCertificateValidTill { get; set; }
        public string NodalOfficerName { get; set; }
        public string StreetAddress { get; set; }
        public Nullable<long> ContactNo { get; set; }
        public string StreetAddress_2 { get; set; }
        public string Email { get; set; }
        public Nullable<long> Fax { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string FuturePlan { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
    }
}
