//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CompDivUnit
    {
        public long CompanyID { get; set; }
        public string Role { get; set; }
        public string CompanyRefNo { get; set; }
        public string IsActive { get; set; }
        public string CompanyName { get; set; }
        public string FactoryName { get; set; }
        public string FactoryRefNo { get; set; }
        public string UnitName { get; set; }
        public string UnitRefNo { get; set; }
        public string FRole { get; set; }
        public string FIsActive { get; set; }
        public string URole { get; set; }
        public string UIsActive { get; set; }
        public long UnitID { get; set; }
        public long FactoryID { get; set; }
    }
}
