//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Chart
    {
        public long CompanyID { get; set; }
        public string CompanyRefNo { get; set; }
        public string CompanyName { get; set; }
        public long FYID { get; set; }
        public Nullable<decimal> ExchangeTotalAmount { get; set; }
        public string FY { get; set; }
    }
}
