//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CompanyProduct
    {
        public string CompanyName { get; set; }
        public Nullable<long> FYID { get; set; }
        public string FY { get; set; }
        public Nullable<long> CountryID { get; set; }
        public string CountryName { get; set; }
        public string ProdLevel1Name { get; set; }
        public string ProdLevel2Name { get; set; }
        public string ProdLevel3Name { get; set; }
        public string PlatName { get; set; }
        public string Nomenclature { get; set; }
        public string TechLevel1Name { get; set; }
        public string TechLevel2Name { get; set; }
        public string NodalOficerName { get; set; }
        public string NodalOfficerEmail { get; set; }
        public string NodalOficerName1 { get; set; }
        public string NodalOfficerEmail2 { get; set; }
        public Nullable<int> Designation { get; set; }
        public string NodalOfficerMobile { get; set; }
        public string NodalOfficerTelephone { get; set; }
        public string NodalOfficerFax { get; set; }
        public string FactoryName { get; set; }
        public string UnitName { get; set; }
        public long ProductID { get; set; }
        public string ProductRefNo { get; set; }
        public string CompanyRefNo { get; set; }
        public Nullable<long> ProductLevel1 { get; set; }
        public Nullable<long> ProductLevel2 { get; set; }
        public Nullable<long> ProductLevel3 { get; set; }
        public string ProductDescription { get; set; }
        public string NSCCode { get; set; }
        public string NIINCode { get; set; }
        public string OEMPartNumber { get; set; }
        public string OEMName { get; set; }
        public Nullable<long> OEMCountry { get; set; }
        public string OEMAddress { get; set; }
        public string DPSUPartNumber { get; set; }
        public string TermConditionImage { get; set; }
        public string HsnCode8digit { get; set; }
        public string EndUser { get; set; }
        public Nullable<long> Platform { get; set; }
        public Nullable<long> NomenclatureOfMainSystem { get; set; }
        public Nullable<long> TechnologyLevel1 { get; set; }
        public Nullable<long> TechnologyLevel2 { get; set; }
        public string IsIndeginized { get; set; }
        public string ManufactureName { get; set; }
        public string ManufactureAddress { get; set; }
        public Nullable<long> YearofIndiginization { get; set; }
        public string PurposeofProcurement { get; set; }
        public string EOIStatus { get; set; }
        public string EOIURL { get; set; }
        public Nullable<long> NodelDetail { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> RecInsTime { get; set; }
        public string Role { get; set; }
        public string IsApproved { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string IsShowGeneral { get; set; }
        public string IndTargetYear { get; set; }
        public string IndProcess { get; set; }
        public string IsProductImported { get; set; }
        public string QAAgency { get; set; }
        public Nullable<long> NodalDetail2 { get; set; }
        public string FeatursandDetail { get; set; }
        public string EOIStartDate { get; set; }
        public string EOIEndDate { get; set; }
        public string SupplyOrderStatus { get; set; }
        public string SupplyManfutureName { get; set; }
        public string SupplyManfutureAddress { get; set; }
        public string supplystartdate { get; set; }
        public string supplyendDate { get; set; }
        public Nullable<System.DateTime> ByDpsuupdatetime { get; set; }
        public string SupplyOrderValue { get; set; }
        public string SupplyDeliveryDate { get; set; }
        public string SupplyOrderDate { get; set; }
        public string ViewOnlyStatus { get; set; }
        public string ViewOnlyReasone { get; set; }
        public Nullable<System.DateTime> IndeginizedDate { get; set; }
        public Nullable<decimal> IndeginizedMaxValue { get; set; }
    }
}
