//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrijanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_IsNodalYes
    {
        public string IsNodalOfficer { get; set; }
        public string NodalOfficerRefNo { get; set; }
        public string NodalOficerName { get; set; }
        public Nullable<int> NodalOfficerDesignation { get; set; }
        public string NodalOfficerEmail { get; set; }
        public string NodalOfficerMobile { get; set; }
        public string NodalOfficerTelephone { get; set; }
        public string NodalOfficerFax { get; set; }
        public string CompanyRefNo { get; set; }
        public string Type { get; set; }
        public string IsActive { get; set; }
    }
}
